// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Data.Entities.Homeİnformation", b =>
                {
                  b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");
                        

                    b.Property<int>("AreaKvMetr")
                        .HasColumnType("int");

                    b.Property<bool>("HomeDocument")
                        .HasColumnType("bit");

                    b.Property<string>("PersonPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoomPhoto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomQuantity")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<int>("ŞəhidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ŞəhidId");

                    b.ToTable("Homeİnformations");
                });

            modelBuilder.Entity("Data.Entities.Şəhid", b =>
                {
                  b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");
                        

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("DateDied")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictDied")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FathersName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FinNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoPassport")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Şəhids");
                });

            modelBuilder.Entity("Data.Entities.ŞəhidMedal", b =>
                {
                  b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");
                        

                    b.Property<DateTime>("MedalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ŞəhidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ŞəhidId");

                    b.ToTable("ŞəhidMedals");
                });

            modelBuilder.Entity("Data.Entities.ŞəhidOvladi", b =>
                {
                  b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");
                        

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PassportPhoto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("ŞəhidId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ŞəhidId");

                    b.ToTable("ŞəhidOvlads");
                });

            modelBuilder.Entity("Data.Entities.Homeİnformation", b =>
                {
                    b.HasOne("Data.Entities.Şəhid", "Şəhid")
                        .WithMany("Homeİnformation")
                        .HasForeignKey("ŞəhidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Şəhid");
                });

            modelBuilder.Entity("Data.Entities.ŞəhidMedal", b =>
                {
                    b.HasOne("Data.Entities.Şəhid", "Şəhid")
                        .WithMany("ŞəhidMedals")
                        .HasForeignKey("ŞəhidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Şəhid");
                });

            modelBuilder.Entity("Data.Entities.ŞəhidOvladi", b =>
                {
                    b.HasOne("Data.Entities.Şəhid", "Şəhid")
                        .WithMany("ŞəhidOvladis")
                        .HasForeignKey("ŞəhidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Şəhid");
                });

            modelBuilder.Entity("Data.Entities.Şəhid", b =>
                {
                    b.Navigation("Homeİnformation");

                    b.Navigation("ŞəhidMedals");

                    b.Navigation("ŞəhidOvladis");
                });
#pragma warning restore 612, 618
        }
    }
}
